### ISSUE TITLE
the dataset cronjob just "can't work" in our current environment

### ISSUE THREAD

**Issue by TomasTomecek** [fedora-copr/log-detective-website#105]
the problem is simple, our quota for memory and storage is:
```
spec:
  hard:
    limits.memory: 2Gi
    memory: 1Gi
    persistentvolumeclaims: '1'
    requests.storage: 5Gi
status:
  used:
    cpu: 300m
    limits.cpu: 750m
    limits.memory: 1399Mi
    memory: 999Mi
    persistentvolumeclaims: '1'
    pods: '2'
    replicationcontrollers: '0'
    requests.storage: 100Mi
```

we have 1 MiB memory left:

- the website pod requests 400MiB but uses right now `log-detective-website-556c8b5b49-zwlz2 268.5 MiB`
- the dataset cronjob requests 599MiB and it's not enough because we download everything in /tmp, which is memory:
```
sh-5.2$ du -sh /tmp/*
0       /tmp/_tmp_json_default-d418f66fdc4ced83_0.0.0_8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96.lock
0       /tmp/json
451M    /tmp/tmphmep058t_log_detective
```

OOMKiller purges the processing:
```
sh-5.2$ python3 /usr/bin/compile_extraction_dataset.py
Reports from Log Detective downloaded
Total 92 files loaded
Generating train split: 0 examples [00:00, ? examples/s]Killed
                                                        ⬆️⬆️⬆️
```

We could create a temp PV and work there but! The limit is only 1 PV and we already use it in the website pod 🙀

I'm honestly clueless right now.
